// =============================================================
// EASTWICK WORKS - artwork data
// One line per work. To add a work: add a line at the right
// position (order = display order), put SLUG.jpg in images/large
// and images/thumb, done. Fields:
//   cat: "color" | "bw" | "sketch"
//   slug: image filename without .jpg
//   title: shown with quotes automatically
//   h / w: dimension lines shown in the lightbox (empty = hidden)
//   sold: true shows a SOLD marker
// =============================================================
const WORKS = [
  { cat: "color", slug: "melting-medley", title: "Melting Medley", h: "Height: 57.2 cm ; 22.5 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "symphonious-bastards", title: "Symphonious Bastards", h: "Height: 73 cm ; 28.7 in", w: "Width: 109.8 cm ; 43.2 in", sold: false },
  { cat: "color", slug: "ursula", title: "Ursula", h: "Height: 73.2 cm ; 28.8 in", w: "Width: 54 cm ; 21.3 in", sold: false },
  { cat: "color", slug: "turtleneck-terror", title: "Turtleneck Terror", h: "Height: 75 cm ; 29.5 in", w: "Width: 61.5 cm ; 24.2 in", sold: false },
  { cat: "color", slug: "moan-zone", title: "Moan Zone", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "color", slug: "simply-suave", title: "Simply Suave", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "color", slug: "streaking-with-strokes", title: "Streaking with Strokes", h: "Height: 73.2 cm ; 28.8 in", w: "Width: 54 cm ; 21.3 in", sold: false },
  { cat: "color", slug: "the-nosefather", title: "The Nosefather", h: "Height: 109.8 cm ; 43.2 in", w: "Width: 73 cm ; 29 in", sold: false },
  { cat: "color", slug: "bright-eyed", title: "Bright-Eyed", h: "Height: 100 cm ; 39.4 in", w: "Width: 100 cm ; 39.4 in", sold: false },
  { cat: "color", slug: "multicolored-melancholy", title: "Multicolored Melancholy", h: "Height: 40 cm ; 15.7 in", w: "Width: 29.8 cm ; 11.7 in", sold: false },
  { cat: "color", slug: "whos-your-daddy", title: "Who's Your Daddy", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "ponzi-scheme", title: "Ponzi Scheme", h: "Height: 50 cm ; 19.7 in", w: "Width: 65 cm ; 25.6 in", sold: false },
  { cat: "color", slug: "no-way-jose", title: "No Way, José", h: "Height: 30 cm ; 11.8 in", w: "Width: 23 cm ; 9 in", sold: false },
  { cat: "color", slug: "lip-sync", title: "Lip Sync", h: "Height: 100 cm ; 39.4 in", w: "Width: 70.2 cm ; 27.6 in", sold: false },
  { cat: "color", slug: "third-dimension", title: "Third Dimension", h: "Height: 109.8 cm ; 43.2 in", w: "Width: 69.8 cm ; 27.5 in", sold: false },
  { cat: "color", slug: "juxtanosing", title: "Juxtanosing", h: "Height: 57.2 cm ; 22.5 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "misunderstood", title: "Misunderstood", h: "Height: 42.4 cm ; 16.7 in", w: "Width: 42.4 cm ; 16.7 in", sold: false },
  { cat: "color", slug: "nose-navigator", title: "Nose Navigator", h: "Height: 80 cm ; 31.5 in", w: "Width: 122.5 cm ; 48.2 in", sold: false },
  { cat: "color", slug: "strange-fruit-symphony", title: "Strange Fruit Symphony", h: "Height: 82 cm ; 32.3 in", w: "Width: 54 cm ; 21.3 in", sold: false },
  { cat: "color", slug: "thirst-trap", title: "Thirst Trap", h: "Height: 58 cm ; 22.9 in", w: "Width: 58 cm ; 22.9 in", sold: false },
  { cat: "color", slug: "jos-woes", title: "Jo's Woes", h: "Height: 64 cm ; 25.2 in", w: "Width: 64 cm ; 25.2 in", sold: false },
  { cat: "color", slug: "jack-of-all-trades", title: "Jack of All Trades", h: "Height: 73.2 cm ; 28.8 in", w: "Width: 54 cm ; 21.3 in", sold: false },
  { cat: "color", slug: "the-face-of-envy", title: "The Face of Envy", h: "Height: 58.7 cm ; 23.1 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "beneath-blue-hues", title: "Beneath Blue Hues", h: "Height: 91 cm ; 35.8 in", w: "Width: 59.7 cm ; 23.5 in", sold: false },
  { cat: "color", slug: "cool-as-canvas", title: "Cool as Canvas", h: "Height: 69.5 cm ; 27.4 in", w: "Width: 49.5 cm ; 19.5 in", sold: false },
  { cat: "color", slug: "godspeed", title: "Godspeed", h: "Height: 88 cm ; 34.6 in", w: "Width: 51 cm ; 20.1 in", sold: false },
  { cat: "color", slug: "jammin-chester", title: "Jammin' Chester", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "meteorological-melancholy", title: "Meteorological Melancholy", h: "Height: 92 cm ; 36.2 in", w: "Width: 65 cm ; 25.6 in", sold: false },
  { cat: "color", slug: "king-fear", title: "King Fear", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "color", slug: "out-cold", title: "Out Cold", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "off-grid", title: "Off Grid", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "loose-cannon", title: "Loose Cannon", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "color", slug: "hide-in-plain-sight", title: "Hide In Plain Sight", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "color", slug: "fixer-upper", title: "Fixer Upper", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "chain-reaction", title: "Chain Reaction", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "color", slug: "caught-red", title: "Caught Red", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "color", slug: "bug-mug", title: "Bug Mug", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "color", slug: "bee-spree", title: "Bee Spree", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "color", slug: "pop-art", title: "Pop Art", h: "Height: 73.2 cm ; 28.8 in", w: "Width: 54 cm ; 21.3 in", sold: false },
  { cat: "color", slug: "dons-atomic-adventure", title: "Don's Atomic Adventure", h: "Height: 92 cm ; 36.2 in", w: "Width: 65 cm ; 25.6 in", sold: false },
  { cat: "color", slug: "lets-get-found", title: "Let's Get Found", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "rainbow-rascal", title: "Rainbow Rascal", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "color", slug: "ingrid", title: "Ingrid", h: "Height: 110 cm ; 43.3 in", w: "Width: 73 cm ; 28.8 in", sold: false },
  { cat: "color", slug: "facing-the-music", title: "Facing the Music", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "freeze-tease", title: "Freeze Tease", h: "Height: 100 cm ; 39.4 in", w: "Width: 72 cm ; 28.3 in", sold: false },
  { cat: "color", slug: "fish-fella", title: "Fish Fella", h: "Height: 36 cm ; 14.2 in", w: "Width: 27 cm ; 10.6 in", sold: false },
  { cat: "color", slug: "wrinkle-twinkle", title: "Wrinkle Twinkle", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "color", slug: "lucid-haze", title: "Lucid Haze", h: "Height: 36 cm ; 14.2 in", w: "Width: 27 cm ; 10.6 in", sold: false },
  { cat: "color", slug: "chill-pill", title: "Chill Pill", h: "Height: 100 cm ; 39.4 in", w: "Width: 72 cm ; 28.3 in", sold: false },
  { cat: "color", slug: "bent-outta-shape", title: "Bent Outta Shape", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "an-inconvenient-ruth", title: "An Inconvenient Ruth", h: "", w: "", sold: false },
  { cat: "color", slug: "bed-head", title: "Bed Head", h: "Height: 59.3 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "blue-monday", title: "Blue Monday", h: "Height: 42 cm ; 16.5 in", w: "Width: 30 cm ; 11.8 in", sold: false },
  { cat: "color", slug: "checkmate", title: "Checkmate", h: "Height: 36 cm ; 14.2 in", w: "Width: 37 cm ; 14.6 in", sold: false },
  { cat: "color", slug: "clarks-day-off", title: "Clark's Day Off", h: "Height: 122 cm ; 48 in", w: "Width: 80 cm ; 31.5 in", sold: false },
  { cat: "color", slug: "eye-tooth", title: "Eye Tooth", h: "Height: 59.3 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "color", slug: "fools-gold", title: "Fool's Gold", h: "Height: 42 cm ; 16.5 in", w: "Width: 30 cm ; 11.8 in", sold: false },
  { cat: "color", slug: "red-nose-day", title: "Red Nose Day", h: "Height: 42 cm ; 16.5 in", w: "Width: 30 cm ; 11.8 in", sold: false },
  { cat: "color", slug: "shades-of-doubt", title: "Shades of Doubt", h: "Height: 80 cm ; 31.5 in", w: "Width: 60 cm ; 23.6 in", sold: false },
  { cat: "color", slug: "star-turn", title: "Star Turn", h: "Height: 42 cm ; 16.5 in", w: "Width: 30 cm ; 11.8 in", sold: false },
  { cat: "color", slug: "steamed-up", title: "Steamed Up", h: "Height: 42 cm ; 16.5 in", w: "Width: 30 cm ; 11.8 in", sold: false },
  { cat: "color", slug: "sunday-smile", title: "Sunday Smile", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "color", slug: "thinking-green", title: "Thinking Green", h: "Height: 100 cm ; 39.4 in", w: "Width: 70.3 cm ; 27.7 in", sold: false },
  { cat: "color", slug: "tools-of-the-trade", title: "Tools of the Trade", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "color", slug: "watered-down", title: "Watered Down", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "bw", slug: "dennis-in-wonderland", title: "Dennis in Wonderland", h: "Height: 69.9 cm ; 27.5 in", w: "Width: 50 cm ; 19.7 in", sold: false },
  { cat: "bw", slug: "the-binger", title: "The Binger", h: "Height: 54 cm ; 21.3 in", w: "Width: 73.2 cm ; 28.8 in", sold: true },
  { cat: "bw", slug: "security-advisor", title: "Security Advisor", h: "Height: 109.8 cm ; 43.2 in", w: "Width: 69.8 cm ; 27.5 in", sold: true },
  { cat: "bw", slug: "under-my-skin", title: "Under My Skin", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "bw", slug: "peyote", title: "Peyote", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "bw", slug: "byrds-blazing-brass", title: "Byrd's Blazing Brass", h: "Height: 55.2 cm ; 21.7 in", w: "Width: 45 cm ; 17.7 in", sold: false },
  { cat: "bw", slug: "snack-jack", title: "Snack Jack", h: "Height: 65 cm ; 25.6 in", w: "Width: 50 cm ; 19.7 in", sold: false },
  { cat: "bw", slug: "desperate-housewife", title: "Desperate Housewife", h: "Height: 73 cm ; 28.7 in", w: "Width: 109.8 cm ; 43.2 in", sold: false },
  { cat: "bw", slug: "el-colonel", title: "El Colonel", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "bw", slug: "lunch-time", title: "Lunch Time", h: "Height: 109.8 cm ; 43.2 in", w: "Width: 69.8 cm ; 27.5 in", sold: false },
  { cat: "bw", slug: "nailing-it", title: "Nailing It", h: "Height: 73.2 cm ; 28.8 in", w: "Width: 54 cm ; 21.3 in", sold: false },
  { cat: "bw", slug: "coffee-on-my-mind", title: "Coffee on My Mind", h: "Height: 73 cm ; 28.7 in", w: "Width: 57 cm ; 22.4 in", sold: false },
  { cat: "bw", slug: "ay-papi", title: "Ay, Papi", h: "Height: 109.8 cm ; 43.2 in", w: "Width: 69.8 cm ; 27.5 in", sold: false },
  { cat: "bw", slug: "liquid-liberty", title: "Liquid Liberty", h: "Height: 73.2 cm ; 28.8 in", w: "Width: 54 cm ; 21.3 in", sold: false },
  { cat: "bw", slug: "spice-it-up", title: "Spice It Up", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "bw", slug: "geometric-gerald", title: "Geometric Gerald", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "bw", slug: "lungo-lizard", title: "Lungo Lizard", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "bw", slug: "ur-in-trouble", title: "Ur In Trouble", h: "Height: 73.2 cm ; 28.8 in", w: "Width: 54 cm ; 21.3 in", sold: false },
  { cat: "bw", slug: "luscious-laylah", title: "Luscious Laylah", h: "Height: 75.3 cm ; 29.7 in", w: "Width: 64.1 cm ; 25.2 in", sold: false },
  { cat: "bw", slug: "troll-patrol", title: "Troll Patrol", h: "Height: 73 cm ; 28.8 in", w: "Width: 54 cm ; 21.3 in", sold: false },
  { cat: "bw", slug: "neoliberal", title: "Neoliberal", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "bw", slug: "polio-pioneer", title: "Polio Pioneer", h: "Height: 65 cm ; 25.6 in", w: "Width: 50 cm ; 19.7 in", sold: false },
  { cat: "bw", slug: "counterstroke", title: "Counterstroke", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "bw", slug: "timber-sly", title: "Timber Sly", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "bw", slug: "chet-regret", title: "Chet Regret", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "bw", slug: "blast-from-the-past", title: "Blast From the Past", h: "Height: 103.5 cm ; 40.7 in", w: "Width: 73 cm ; 28.7 in", sold: false },
  { cat: "bw", slug: "lisa-crimson", title: "Lisa Crimson", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "bw", slug: "jiving-clive", title: "Jiving Clive", h: "Height: 59 cm ; 23.2 in", w: "Width: 46 cm ; 18.1 in", sold: false },
  { cat: "bw", slug: "sax-scene-snapshot", title: "Sax Scene Snapshot", h: "Height: 73.2 cm ; 28.8 in", w: "Width: 54 cm ; 21.3 in", sold: false },
  { cat: "bw", slug: "nicotine-nancy", title: "Nicotine Nancy", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "bw", slug: "marital-bliss", title: "Marital Bliss", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "bw", slug: "udderly-divine", title: "Udderly Divine", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "bw", slug: "lurking-louboutin", title: "Lurking Louboutin", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "bw", slug: "the-last-suck", title: "The Last Suck", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "bw", slug: "facing-facts", title: "Facing Facts", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "bw", slug: "finger-food", title: "Finger Food", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "bw", slug: "dino-dictator", title: "Dino Dictator", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "bw", slug: "top-heavy-tweety", title: "Top-Heavy Tweety", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "bw", slug: "sock-lobster", title: "Sock Lobster", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "bw", slug: "blandness-in-bloom", title: "Blandness in Bloom", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "bw", slug: "inside-out", title: "Inside Out", h: "Height: 59.2 cm ; 23.3 in", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "bw", slug: "hernia", title: "Hernia", h: "Height: 19 cm ; 7.5 in", w: "Width: 13.5 cm ; 5.3 in", sold: false },
  { cat: "sketch", slug: "kimberly", title: "Kimberly", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "piotr", title: "Piotr", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "inflated-intimacy", title: "Inflated Intimacy", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "weathered-by-time", title: "Weathered by Time", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "crestfallen", title: "Crestfallen", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "color-me-impressed", title: "Color Me Impressed", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "still-got-it", title: "Still Got It", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "pensive-in-pink", title: "Pensive in Pink", h: "Height: 42 cm ; 16.5 in", w: "Width: 59.2 cm ; 23.3 in", sold: false },
  { cat: "sketch", slug: "tough-ride", title: "Tough Ride", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "headliner", title: "Headliner", h: "Height: 32 cm ; 12.6 in", w: "Width: 23.5 cm ; 9.2 in", sold: false },
  { cat: "sketch", slug: "bender", title: "Bender", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "eye-on-the-prize", title: "Eye on the Prize", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "open-mouthed-meltdown", title: "Open-Mouthed Meltdown", h: "Height: 29.7 cm ; 11.7 in ", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "sketch", slug: "nighttime-nibbles", title: "Nighttime Nibbles", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "sketch", slug: "the-making-of-maya", title: "The Making of Maya", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "cup-of-madge", title: "Cup of Madge", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "head-over-wheels", title: "Head over Wheels", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "sketch", slug: "wings-n-things", title: "Wings 'n' Things", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "match-made-in-heaven", title: "Match Made in Heaven", h: "Height: 36 cm ; 14.2 in", w: "Width: 27 cm ; 10.6 in", sold: false },
  { cat: "sketch", slug: "h2-oh-no", title: "H2-Oh No!", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "mint-condition", title: "Mint Condition", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "cup-of-joe", title: "Cup of Joe", h: "Height: 24 cm ; 9.5 in", w: "Width: 18 cm ; 7.2 in", sold: false },
  { cat: "sketch", slug: "me-myself-and-yellow", title: "Me, Myself, and Yellow", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "sketch", slug: "handy-haze", title: "Handy Haze", h: "Height: 29.7 cm ; 11.7 in ", w: "Width: 42 cm ; 16.5 in", sold: false },
  { cat: "sketch", slug: "handsome", title: "Handsome", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "a-bit-of-a-mess", title: "A Bit of a Mess", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "buzzing-for-a-bite", title: "Buzzing for a Bite", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "firefly-felon", title: "Firefly Felon", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "loud-and-clear", title: "Loud and Clear", h: "Height: 29 cm ; 11.4 in", w: "Width: 20.4 cm ; 8 in", sold: false },
  { cat: "sketch", slug: "antonio", title: "Antonio", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "food-for-the-sole", title: "Food for the Sole", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "medi-bug", title: "Medi-bug", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "the-dribbler", title: "The Dribbler", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "drip-happens", title: "Drip Happens", h: "Height: 20 cm ; 7.9 in", w: "Width: 12.2 cm ; 4.8 in", sold: false },
  { cat: "sketch", slug: "tipsy-on-textures", title: "Tipsy on Textures", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "sketch", slug: "call-me-maybe", title: "Call Me Maybe", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "moody-me", title: "Moody Me", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "facial-fountain", title: "Facial Fountain", h: "Height: 42 cm ; 16.5 in", w: "Width: 29.7 cm ; 11.7 in", sold: false },
  { cat: "sketch", slug: "wire-sire", title: "Wire Sire", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "swirl-earl", title: "Swirl Earl", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "strung-out", title: "Strung Out", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "snack-attack", title: "Snack Attack", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "seventh-sense", title: "Seventh Sense", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "mind-maze", title: "Mind Maze", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "giddy-gazebo", title: "Giddy Gazebo", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "fusion-confusion", title: "Fusion Confusion", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "fire-it-up", title: "Fire It Up", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "crunch-time", title: "Crunch Time", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "cig-gig", title: "Cig Gig", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "cheeky-chic", title: "Cheeky Chic", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "absent-minded", title: "Absent Minded", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "aim-low", title: "Aim Low", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "backwards-thinking", title: "Backwards Thinking", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "best-foot-forward", title: "Best Foot Forward", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "boxed-in", title: "Boxed In", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "brewing-trouble", title: "Brewing Trouble", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "bubble-brain", title: "Bubble Brain", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "bubble-trouble", title: "Bubble Trouble", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "chamber-music", title: "Chamber Music", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "checkered-past", title: "Checkered Past", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "chin-rest", title: "Chin Rest", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "curl-power", title: "Curl Power", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "domestic-bliss", title: "Domestic Bliss", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "drink-me", title: "Drink Me", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "ear-for-music", title: "Ear for Music", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "fashion-hound", title: "Fashion Hound", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "flower-power-steering", title: "Flower Power Steering", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "framed", title: "Framed", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "gentle-giant", title: "Gentle Giant", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "growing-pains", title: "Growing Pains", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "hairline-fracture", title: "Hairline Fracture", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "hammer-time", title: "Hammer Time", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "hand-hound", title: "Hand Hound", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "hands-up", title: "Hands Up", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "hot-set", title: "Hot Set", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "juggling-act", title: "Juggling Act", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "last-drop", title: "Last Drop", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "lid-kid", title: "Lid Kid", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "loose-ends", title: "Loose Ends", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "melon-mobile", title: "Melon Mobile", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "ode-to-british-tourism", title: "Ode to British Tourism", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "off-the-hook", title: "Off the Hook", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "one-wheel-wonder", title: "One Wheel Wonder", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "open-mic-night", title: "Open Mic Night", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "peace-of-mind", title: "Peace of Mind", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "pencil-pusher", title: "Pencil Pusher", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "pillow-talk", title: "Pillow Talk", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "pop-goes-the-easel", title: "Pop Goes the Easel", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "punk-grandpa", title: "Punk Grandpa", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "royal-flush", title: "Royal Flush", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "say-cheese", title: "Say Cheese", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "screwball", title: "Screwball", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "shell-shock", title: "Shell Shock", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "shoulder-angel", title: "Shoulder Angel", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "sinking-feeling", title: "Sinking Feeling", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "sound-check", title: "Sound Check", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "spilt-milk", title: "Spilt Milk", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "state-of-the-union", title: "State of the Union", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "stirring-stuff", title: "Stirring Stuff", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "storm-in-a-teacup", title: "Storm in a Teacup", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "straw-poll", title: "Straw Poll", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "strike-a-pose", title: "Strike a Pose", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "suit-yourself", title: "Suit Yourself", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "thumbs-up", title: "Thumbs Up", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "tour-de-farce", title: "Tour de Farce", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "twerk-in-progress", title: "Twerk in Progress", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "unplugged", title: "Unplugged", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "up-in-smoke", title: "Up in Smoke", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "waist-land", title: "Waist Land", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "wall-of-sound", title: "Wall of Sound", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
  { cat: "sketch", slug: "warm-front", title: "Warm Front", h: "Height: 29.7 cm ; 11.7 in", w: "Width: 21 cm ; 8.3 in", sold: false },
];

// Works featured on the home page, by slug, in display order.
const FEATURED = [
  "moan-zone",
  "desperate-housewife",
  "facing-the-music",
  "kimberly",
  "melting-medley",
  "the-binger",
  "an-inconvenient-ruth",
  "lunch-time",
];
